export const FETCH_DAILY_WEATHER = 'weather/FETCH_DAILY_WEATHER';
export const FETCH_HOURLY_WEATHER = 'weather/FETCH_HOURLY_WEATHER';
export const FETCH_CURRENT_WEATHER = 'weather/FETCH_CURRENT_WEATHER';
export const WEATHER_CACHED = 'weather/WEATHER_CACHED';
